// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/token_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepo is a mock of TokenRepo interface.
type MockTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepoMockRecorder
	isgomock struct{}
}

// MockTokenRepoMockRecorder is the mock recorder for MockTokenRepo.
type MockTokenRepoMockRecorder struct {
	mock *MockTokenRepo
}

// NewMockTokenRepo creates a new mock instance.
func NewMockTokenRepo(ctrl *gomock.Controller) *MockTokenRepo {
	mock := &MockTokenRepo{ctrl: ctrl}
	mock.recorder = &MockTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepo) EXPECT() *MockTokenRepoMockRecorder {
	return m.recorder
}

// GetCachedToken mocks base method.
func (m *MockTokenRepo) GetCachedToken(ctx context.Context, userId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedToken", ctx, userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedToken indicates an expected call of GetCachedToken.
func (mr *MockTokenRepoMockRecorder) GetCachedToken(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedToken", reflect.TypeOf((*MockTokenRepo)(nil).GetCachedToken), ctx, userId)
}

// SetCachedToken mocks base method.
func (m *MockTokenRepo) SetCachedToken(ctx context.Context, userId, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetCachedToken", ctx, userId, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetCachedToken indicates an expected call of SetCachedToken.
func (mr *MockTokenRepoMockRecorder) SetCachedToken(ctx, userId, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCachedToken", reflect.TypeOf((*MockTokenRepo)(nil).SetCachedToken), ctx, userId, token)
}
